# Site Settings
title: "My Cosmology Website"
email: vardanyanv@gmail.com
description: >
  My personal website.
baseurl: "/"
url: "http://valerivardanyan.github.io"
github_username:  valerivardanyan
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
